# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "uas" "usbhid" "usb_storage" "sd_mod" "sr_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];
  boot.kernelParams = ["usbcore.autosuspend=-1"];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/55e6a024-d3a6-4827-b734-32f80119284e";
    fsType = "ext4";
  };
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/BD2B-D0E8";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  fileSystems."/mnt/mass" = {
    device = "/dev/disk/by-uuid/e59ec576-6efd-4f7f-bd91-b39b6b16ee46";
    fsType = "ext4";
    options = ["nofail" "defaults"];
  };

  # Auto-remount the USB mass storage when it reconnects after a glitch
  # (e.g. kernel renames sda → sdb). Without this udev rule the mount
  # goes stale and returns EIO until a manual umount + mount.
  services.udev.extraRules = ''
    ACTION=="add", SUBSYSTEM=="block", ENV{ID_FS_UUID}=="e59ec576-6efd-4f7f-bd91-b39b6b16ee46", \
      RUN+="/run/current-system/sw/bin/systemctl --no-block restart mnt-mass.mount"
  '';

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
