name: Proxmox VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TAILSCALE_VERSION: 1.84.0

jobs:
  build-vm:
    name: Build Proxmox VM image and upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Unlock git-crypt
        run: |
          sudo apt-get update
          sudo apt-get install -y git-crypt
          echo ${{ secrets.GIT_CRYPT_KEY }} | base64 -d | git-crypt unlock -

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build proxmox VM image
        run: |
          nix build '.#nixosConfigurations.default.config.system.build.images.proxmox'

      - name: Rename VMA
        run: |
          VMA=$(find -L ./result -name "vzdump-qemu-*.vma.zst" -type f)
          cp -L "$VMA" /tmp/vzdump-qemu-nixos-proxmox-default.vma.zst

      - name: Setup Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_CLIENT_SECRET }}
          tags: tag:github-actions
          version: ${{ env.TAILSCALE_VERSION }}

      - name: Setup SSH
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_ed25519
          echo "${{ secrets.PVE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          echo "${{ secrets.PVE_SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Upload to PVE
        env:
          PVE_HOST: ${{ secrets.PVE_HOST }}
          PVE_SSH_USER: ${{ secrets.PVE_SSH_USER }}
        run: |
          scp /tmp/vzdump-qemu-nixos-proxmox-default.vma.zst \
            "$PVE_SSH_USER@$PVE_HOST:/var/lib/vz/dump/vzdump-qemu-nixos-proxmox-default.vma.zst"

      - name: Lock git-crypt
        run: |
          git-crypt lock

      - name: Delete local output
        run: |
          rm -rf ./result
          rm -f /tmp/vzdump-qemu-nixos-proxmox-default.vma.zst
